#!/bin/sh -e

# We keep track of the Common Working Directory (cwd) using a file:
tmpfile=/tmp/cwd_"$USER" # default value

while getopts ':f:w:r' opt; do
    case $opt in
        f) # Specify the file for the following operation.
            tmpfile=$OPTARG
            ;;
        w) # Write arg to the file. Use this to set the cwd.
            echo "$OPTARG" > "$tmpfile"
            exit 0
            ;;
        r) # Return file contents. Use this to get the cwd.
            if ! [ -e "$tmpfile" ]; then # create if doesn't exist
                install -m 600 /dev/null "$tmpfile"
                echo "$HOME" > "$tmpfile"
            fi
            cat "$tmpfile"
            exit 0
            ;;
        *) break
    esac
done

>&2 cat <<EOF
Usage:  cwd [-f cwd_file] -w dir_name
        cwd [-f cwd_file] -r

Options:
       -f cwd_file: use given file for cwd_file instead of the
                    default (/tmp/cwd_$USER)
       -w dir_name: write dir_name to cwd_file
       -r:          get CWD from cwd_file

EOF
exit 1
